version: '3'

services:
  app:
    build: ../route_api
    restart: on-failure
    container_name: route_api
    ports:
      - "8080:8080"
    environment:
      - OPENROUTESERVICE_API_KEY=${openrouteservice_api_key}